### ISSUE TITLE
notification queue client not able to pull lifecycle events from Engflow cluster

### ISSUE THREAD

**Issue by drwx** [EngFlow/example#70]
[Client](https://github.com/EngFlow/example/tree/main/java/com/engflow/notificationqueue)

Command:
```
$> bazel run //java/com/engflow/notificationqueue:client \ 
-- --notification_queue_endpoint=grpc://demo.cluster.engflow.com --queue_name=default/eventstore/lifecycle-events 
INFO: Running command line: bazel-bin/java/com/engflow/notificationqueue/client '--notification_queue_endpoint=grpc://demo.cluster.engflow.com' '--queue_name=default/eventstore/lifecycle-events'
Listening for build events...
Error on request: UNAVAILABLE: io exception
```
Irrespective of build events on the cluster, it always fails after ~36 seconds.

If `grpcs` is used with valid tls_certificate and tls_key, it is not failing but returns immediately with no result.

```
INFO: Running command line: bazel-bin/java/com/engflow/notificationqueue/client '--notification_queue_endpoint=grpcs://demo.cluster.engflow.com' '--queue_name=default/eventstore/lifecycle-events' '--tls_certificate=/Users/vijay/tmp/canary_latest/engflow.crt' '--tls_key=/Users/vijay/tmp/canary_latest/engflow.key'
Listening for build events...
Finished pulling notifications
```

Note: the client README suggests `--queue_name` to be  `eventstore/lifecycle-events` but the actual queue name registered in the backend is `default/eventstore/lifecycle-events`.

**Comment by anfelbar** [comment]
We need to first activate `--eventstore_publish_lifecycle_events`. I will add that info to the example.

**Comment by anfelbar** [comment]
I have checked with `Opal` and `Envoy` and it is failing. Looks like the connection is not getting accepted. I will look what have changed in `engflow/engflow` and `engflow/prod` because the` engflow/example` have not been touched.

**Comment by anfelbar** [comment]
I am running a local cluster with no auth, I get this error when using the API with the example:

```
W 2023-03-01 16:24:30.387 thread=engflow-scheduler-default-4 [com.engflow.notificationqueue.grpc.NotificationQueueServiceV1$1.onFailure] Error reading client stream
java.lang.NullPointerException
	at com.engflow.util.grpc.AsyncStreamGrpcClientResponseObserver.requestElementFromClient(AsyncStreamGrpcClientResponseObserver.java:61)
	at com.engflow.util.grpc.AsyncStreamGrpcClientResponseObserver.lambda$fetchNext$0(AsyncStreamGrpcClientResponseObserver.java:84)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:250)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:240)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:851)
	at com.google.common.util.concurrent.SettableFuture.setFuture(SettableFuture.java:61)
	at com.engflow.util.grpc.AsyncStreamGrpcClientResponseObserver.add(AsyncStreamGrpcClientResponseObserver.java:160)
	at com.engflow.util.grpc.AsyncStreamGrpcClientResponseObserver.onNext(AsyncStreamGrpcClientResponseObserver.java:133)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at com.engflow.util.threading.MetricReportingScheduledThreadPoolExecutor$InstrumentedTask.run(MetricReportingScheduledThreadPoolExecutor.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I will continue digging but it is difficult to know what change in the past months. I will keep you informed.

**Comment by anfelbar** [comment]
Well, I have isolated the commit that "broke" the example: https://github.com/EngFlow/engflow/commit/fe749dad7b33391c508a383796f14f93b8bae24d
1. I will try to change the example in order to be compatible with the changed in engflow/engflow.
2. After that, I will try to add a test for this against opal, so we can capture if we break things here.

**Comment by drwx** [comment]
Filed a[ backend bug](https://github.com/EngFlow/engflow/issues/13461), it shouldn't throw NPE even when the client is holding it wrong.

**Comment by anfelbar** [comment]
https://github.com/EngFlow/engflow/pull/13476 Fixed the issue.

**Comment by anfelbar** [comment]
https://github.com/EngFlow/engflow/issues/13477
